import type { Metadata } from "next";
import "./globals.css";
import { PersistentLogoutButton } from "@/components/auth/PersistentLogoutButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <PersistentLogoutButton />
        {children}
      </body>
    </html>
  );
}
