import type { Metadata } from "next";
import "./globals.css";
import { PersistentLogoutButton } from "@/components/auth/PersistentLogoutButton";
import Iridescence from "@/components/layout/Iridescence";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <Iridescence
          color={[1, 0.6, 0.8]}
          mouseReact
          amplitude={0.1}
          speed={0.9}
        />
        <PersistentLogoutButton />
        {children}
      </body>
    </html>
  );
}
